FROM node:18.16.0-alpine as site-base

WORKDIR /app
COPY ./react-site /app
RUN npm config delete proxy
RUN npm install
RUN npm run build

FROM nginx:latest

COPY --from=site-base /app/build /usr/share/nginx/html
COPY ./etc/nginx.conf /etc/nginx/conf.d/default.conf
