version: '1.0'

volumes:
  web_homework_db:

services:
  web_homework_db:
    image: postgres
    container_name: web_homework_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shop
    ports:
      - "5432:5432"
    volumes:
      - web_homework_db:/var/lib/postgresql/data
