version: '1.0'

volumes:
  web_homework_db:

networks:
  web_homework_network:
    name: web_homework_network

services:
  web_homework_db:
    image: postgres
    container_name: web_homework_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shop
    ports:
      - "5432:5432"
    volumes:
      - web_homework_db:/var/lib/postgresql/data
    networks:
      - web_homework_network

  web_homework_redis:
    image: redis
    container_name: web_homework_redis
    ports:
      - "6379:6379"
    networks:
      - web_homework_network

  web_homework_mongo:
    container_name: web_homework_mongo
    image: mongo:4.4.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    networks:
      - web_homework_network

  web_homework_api:
    build:
      context: .
      dockerfile: ./Dockerfile.api.yaml
    container_name: web_homework_api
    environment:
      API_RUN_PORT: 8080
      API_DB_HOST: web_homework_db
      API_DB_PORT: 5432
      API_DB_NAME: shop
      API_DB_USER: postgres
      API_DB_PASSWORD: postgres
      API_REDIS_HOST: web_homework_redis
      API_REDIS_PORT: 6379
      API_MONGO_USER: admin
      API_MONGO_PASSWORD: admin
      API_MONGO_HOST: web_homework_mongo
      API_MONGO_PORT: 27017
      API_MONGO_DB: shop
      API_SECRET: i_am_secret_lol
    ports:
      - "8080:8080"
    networks:
      - web_homework_network
    volumes:
      - "./api:/api"
    depends_on:
      - web_homework_db
      - web_homework_redis
      - web_homework_mongo

  web_homework_site:
    build:
      context: .
      dockerfile: ./Dockerfile.site.yaml
    container_name: web_homework_site
    ports:
      - "80:80"
    networks:
      - web_homework_network
    depends_on:
      - web_homework_api
