FROM debian

EXPOSE 80

RUN apt update && \
    apt install -y apache2 && \
    apt install -y php libapache2-mod-php

RUN ln -sf /proc/self/fd/1 /var/log/apache2/access.log && \
    ln -sf /proc/self/fd/1 /var/log/apache2/error.log

VOLUME ["/var/www/site"]

RUN a2dissite 000-default

CMD ["apachectl", "-D", "FOREGROUND"]
